import 'dart:ui';

class allData
{
  static Color darkGreen=Color.fromARGB(255, 0, 151, 136);
  static Color lightGreen=Color.fromARGB(255, 224, 242, 242);
  static Color disabledBtn=Color.fromARGB(255, 166, 218, 214);
  static List image=[
    "aguacate.png",
    "ajo.png",
    "ardilla.png",
    "barco.png",
    "bellota.png",
    "bombon.png",
    "cerezas.png",
    "ciruela.png",
    "coche.png",
    "coco.png",
    "cono.png",
    "copa.png",
    "cubo.png",
    "delfin.png",
    "flamenco.png",
    "galleta.png",
    "gato.png",
    "globo.png",
    "hamburguesa.png",
    "hoja_otoño.png",
    "loro.png",
    "margarita.png",
    "naranja.png",
    "oso.png",
    "paloma.png",
    "paraguas.png",
    "pelota_baloncesto.png",
    "peon.png",
    "perfume.png",
    "perro.png",
    "pimiento.png",
    "pinguino.png",
    "platano.png",
    "queso.png",
    "reloj.png",
    "rosa.png",
    "silla.png",
    "telefono.png",
    "trebol.png",
    "caracol.png",
    "calabaza.png",
    "uvas.png",
    "vaca.png",
    "vela.png",
    "campana.png",
    "ventilador.png",
    "zanahoria.png",
    "caballo.png",
    "zapatos.png",
  ];
}